### ISSUE TITLE
incorrect content length for string 

### ISSUE THREAD

**Issue by vake** [mulesoft/s3-connector#14]
In S3ContentUtils.java,

    private static S3ObjectContent createContent(String contentMd5, String stringContent)
    {
        return new InputStreamS3ObjectContent(new ByteArrayInputStream(stringContent.getBytes()),
             (long) stringContent.length(), contentMd5);
    }

If a string is wrapped in an inputstream object, the actual byte length should be used, otherwise the last few bytes might get truncated by s3. "stringContent.length()" only gives you the character count, while "stringContent.getBytes().length" gives you you the actual size.

**Comment by veigap** [comment]
This is also a bug in the code: stringContent.getBytes() should specify the encodding..

**Comment by karthikanantha** [comment]
The bug has been fixed and will be available once the current v3.0.0 is released.
